import mongoose, { Schema, Document } from 'mongoose';

export type WalletVersion = 'v4r2' | 'v5r1';

export interface IWallet extends Document {
  userId: mongoose.Types.ObjectId;

  /**
   * The actual on-chain wallet address.
   */
  address: string;

  /**
   * Encrypted 24-word mnemonic.
   */
  encryptedMnemonic: string;

  /**
   * Encryption IV.
   */
  iv: string;

  /**
   * Encryption authentication tag.
   */
  tag: string;

  /**
   * Whether this wallet was imported by the user
   * or generated by the bot.
   */
  isImported: boolean;

  /**
   * Wallet contract/version used to derive the address.
   *
   * v4r2 = TON Wallet V4R2
   * v5r1 = TON Wallet V5R1 / W5
   *
   * Optional so existing database documents created before
   * this field existed do not immediately break.
   */
  walletVersion?: WalletVersion;

  createdAt: Date;
  updatedAt: Date;
}

const WalletSchema = new Schema<IWallet>(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    /**
     * TON address.
     *
     * unique prevents accidentally importing the exact
     * same wallet address multiple times.
     */
    address: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    /**
     * Encrypted mnemonic.
     */
    encryptedMnemonic: {
      type: String,
      required: true,
    },

    /**
     * AES-GCM IV.
     */
    iv: {
      type: String,
      required: true,
    },

    /**
     * AES-GCM authentication tag.
     */
    tag: {
      type: String,
      required: true,
    },

    /**
     * false = wallet generated by bot
     * true  = wallet imported by user
     */
    isImported: {
      type: Boolean,
      default: false,
      index: true,
    },

    /**
     * Wallet contract version.
     *
     * Existing documents may not have this field.
     * The WalletService will detect/backfill V4 wallets
     * when they are used.
     */
    walletVersion: {
      type: String,
      enum: ['v4r2', 'v5r1'],
      required: false,
      default: undefined,
      index: true,
    },
  },
  {
    timestamps: true,
  }
);

export const Wallet = mongoose.model<IWallet>(
  'Wallet',
  WalletSchema
);
